Mohammad
MSF-OCB/bahmni-docker pull request #7
Opened 2021-05-31 09:52 UTC by munnavhai

2021-05-31 10:08 UTC, MahmoudAbdo2020 submitted a review, later dismissed

2021-05-31 10:20 UTC, R-VdP requested changes

2021-05-31 10:20 UTC, R-VdP commented on stage1/roles/setup_installer/tasks/main.yml
> +  raw: easy_install --always-unzip --allow-hosts=None /opt/Click-7.0.tar.gz
Where should we find this zip? Maybe better to host it somewhere or add it here, otherwise we'll get stuck in the future.

2021-05-31 10:25 UTC, munnavhai commented on stage1/roles/setup_installer/tasks/main.yml
> +  raw: easy_install --always-unzip --allow-hosts=None /opt/Click-7.0.tar.gz
Its in /opt/PROJECT/bahmni/artifacts/misc_stage1/

2021-05-31 10:26 UTC, R-VdP commented on stage1/roles/setup_installer/tasks/main.yml
> +  raw: easy_install --always-unzip --allow-hosts=None /opt/Click-7.0.tar.gz
Yeah, on a specific server, I'd like the installation to be able to be run from anywhere, not to depend on a fixed server.

2021-05-31 10:26 UTC, R-VdP commented on stage1/roles/setup_installer/tasks/main.yml
> +  raw: easy_install --always-unzip --allow-hosts=None /opt/Click-7.0.tar.gz
One idea: you could host the zip in a specific branch and host that branch with github pages, and then use the link to download it in the ansible playbook.

2021-05-31 11:06 UTC, R-VdP commented
@munnavhai we do not want the zip in the main branch, this is very inefficient.
We should put it in a separate branch that is hosted with github pages,

2021-06-01 14:07 UTC, R-VdP approved these changes

2021-06-01 14:11 UTC, merged